### PR TITLE
One half: Created a new branch 

### PR DESCRIPTION
**Pull request by rasheedmhd**
I created a branch called one-half. This is where I will be working henceforth. If I make any changes to Symmetry I will push them upstream on the one-half branch and make a Pull Request. 

This branch comes with works I have done in that fixes some of the current issues.
Fixes includes:
1. https://github.com/yawboakye/symmetry/issues/1
2. https://github.com/yawboakye/symmetry/issues/2
3. https://github.com/yawboakye/symmetry/issues/3
4. https://github.com/yawboakye/symmetry/issues/4
5. https://github.com/yawboakye/symmetry/issues/5

### CODE REVIEW

**Comment by yawboakye** [comment]
@rasheedmhd instead of `remove_column` and `add_column` use [`rename_column`](https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/rename_column).

**Comment by rasheedmhd** [comment]
Alright, took a look. Makes sense 🙏🏾

Thanks

**Comment by yawboakye** [comment]
@rasheedmhd in order to undo the migrations, run `rails db:rollback` until all the changes are undone. you can verify this by looking at the annotation comments and/or the database schema in `schema.rb`. take the opportunity to read the `rails db:rollback` doc. then define the migrations with `rename_column`. before defining any migration, figure out if there's a proper API you can use. the migration APIs are documented here: https://api.rubyonrails.org/classes/ActiveRecord/Migration.html.

after the changes, perform a forward migration (rollback is a backwards migration), and update your PR.

**Comment by yawboakye** [comment]
closing because it has been affected by another pr. please submit a new one.

**Pull request closed without merging**
